### PR TITLE
refactor: use ImperativeRef so it's integrated into the Perspective Camera

### PR DESCRIPTION
**Pull request by joshuaellis**
Also tidy up Type usage to make easier

### CODE REVIEW

**Comment by joshuaellis** [comment]
I've had a look at the code & i've tidied it up to reflect some of the other modifier's we have in the repo e.g `useEdgeSplit`. It's not finished because the animation effect is huge (if you run storybook you'll see lol) but ngl, i don't know how to fix it right now and I haven't got time left today. But i'd rather you see the core changes to the API and we can discuss a bit more. Hopefully you can see how it's a bit tidier and less noise in the API?

**Comment by Code47X** [comment]
@joshuaellis Wow thanks this is awesome, its much cleaner. I need to read up on `useImperitiveHandle`.

**Comment by Code47X** [comment]
@joshuaellis The main issue, and I think what's causing the animation to be messed up, is that the yaw/pitch/roll are being applied to the defaultCamera each frame, compounding on itself. yaw/pitch/roll are more like final offsets to be applied on top of a given position/rotation. So I think for this type of animation we are always going to need to be a need to keep a separate shakycam object. It copies its position/rotation each frame for the calculation, but doesn't modify defaultCamera directly.

**Comment by joshuaellis** [comment]
Yeah, I’m not *super* familiar with its usage, but it seems to work here. So take my implementation with a pinch of salt. 

Okay, that makes a bit more sense then, so it adds the offset for a single frame, then resets the camera back to its OG settings. Hm. There’s probably a way round it, thanks for explaining. I’ll have a think too.

**Pull request merged**
